routes/web.php
<?php

// use Symfony\Component\Routing\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout', function () {
    // return abort(404);
    return redirect('/');
});

Route::group(['middleware' => ['auth']], function () {

// Route::get('/location', 'FirebaseController@index');
    // Route::get('/location', function(){
    //     return view ('Location.location');
    // });

// -------------------------------------------------------------- location
    Route::get('/agentforappraisal/{id}/{lat}/{lng}', 'AppraisalController@agentAppraisal');

    Route::get('/execTestRoute', function () {
        return view('execTestRoute');
    })->middleware('executive');

////////////////////////////  add user  /////////////////////////////////////////
    // Route::get('/account/adduser', 'AccountController@addUser')->middleware('admin');
    Route::resource('/account', 'AccountController');

// Route::group(['middleware' => ['auth', 'admin', 'executive']], function () {
    // Route::get('/home', function () {
    //     // return view('admin.dashboard');
    // });
    Route::get('/home', 'HomeController@index');
    Route::get('/home/chrtNreport', 'HomeController@chrtNreport');

//------------------Branch Routs-----------------------

    Route::resource('branch', 'Branch\BranchController');
// Route::get('/showBranch','Branch\BranchController@index');
    //  Route::get('/addbranch','Branch\BranchController@create');
    // Route::get('/storebranch','Branch\BranchController@store');

//------------------Center Routs-----------------------

    Route::resource('center', 'Center\CenterController');
    Route::get('centeri', 'Center\CenterController@index');
    Route::resource('centerleader', 'Center\CenterLeadersController');
    Route::get('/center/edit/{id}', 'Center\CenterLeadersController@edit');
    Route::get('/center/update/{id}', 'Center\CenterLeadersController@update');

//------------------Category Routs---------------------

    Route::resource('category', "CategoryController");
// Route::resource('loan', 'LoanController');

//------------------Routes borrower-------------------

    Route::resource('borrower', 'BorrowerController');
    Route::get('/addborrower', 'BorrowerController@create');
    Route::get('/borrowers', 'BorrowerController@all');
    Route::get('/getcentername', 'BorrowerController@getCenterName');
    Route::get('/getrightcenters', 'BorrowerController@getRightCenters');
    Route::get('/getborrowerscount', 'BorrowerController@getBorrowersCount');
    Route::get('/getborrowerscountofgroup', 'BorrowerController@getborrowerscountofgroup');
    Route::post('/addborrowerajax', 'BorrowerController@addBorrowerAjax');
    Route::get('/borrower/show/{id}', 'BorrowerController@show');
    Route::get('/borrower/edit/{id}', 'BorrowerController@edit');
    Route::get('/addborrower/deleteborrower/{branch}/{center}/{group}', 'BorrowerController@addBorrowerDeleteBorrower');
    Route::post('/addborrower/deleteborrower/{id}', 'BorrowerController@deleteBorrowerChangeVisibility');

    Route::post('/getnic', 'BorrowerController@getNIC');
    Route::post('/checkguardiannic', 'BorrowerController@checkGuardianNIC');

//------------------Loans----------------------------

    Route::resource('loan', 'Loans\LoanController');
    Route::get('/loan/create/rate', 'Loans\LoanController@rate');

    Route::post('/loan/create/addwitness', 'Loans\LoanController@addWitness');
    Route::get('/loan/create/getwitness', 'Loans\LoanController@getWitness');

    Route::get('/loan/create/addbcg', 'Loans\LoanController@addBCG');
    Route::get('/loan/create/witness', 'Loans\LoanController@witness');
    Route::get('/loan/create/take', 'Loans\LoanController@take');

    Route::get('/addloan/getcenters', 'Loans\LoanController@getCenters');
    Route::get('/addloan/getborrowers', 'Loans\LoanController@getBorrowers');
    Route::get('/addloan/getborrowersforrep', 'Loans\LoanController@getBorrowersForRep');
    Route::get('/addloan/getborrowersbynic', 'Loans\LoanController@getBorrowersbynic');
    Route::get('/addloan/getwitnessc', 'Loans\LoanController@getWitnessC');
    Route::get('/addloan/getwitnessa', 'Loans\LoanController@getWitnessA');
    Route::get('/addloan/getloanstage', 'Loans\LoanController@getLoanStage');
    Route::post('/addloanajax', 'Loans\LoanController@store');
    Route::get('/checkcenterleader', 'Loans\LoanController@checkCenterLeader');

//------------------Appraisal-------------------------

    Route::resource('appraisal', 'AppraisalController');
    Route::resource('appraisalearning', 'addAppraisalEarningProductController');
    Route::resource('appraisalcategory', 'addAppraisalProductCategoryController');
    Route::resource('appraisalingredients', 'addAppraisalExpensesProductController');
    Route::post('addAppraisalExpensesProduct', 'addAppraisalExpensesProductController@addAppraisalExpensesProduct');
    Route::get('/createapprasialpage', 'AppraisalController@createAppraisalPage');
    Route::get('/createapprasialpage/products', 'AppraisalController@getUnitPrice');
    Route::get('/createapprasialpage/products', 'AppraisalController@getUnitPrice');
    Route::get('/createapprasialpage/expenses', 'AppraisalController@getExpenses');
    Route::post('/getnicappraisals', 'AppraisalController@getNicAppraisals');
    Route::get('/delprevapp', 'AppraisalController@delPrevApp');
    Route::post('/createapprasialpage/earnings/delearning', 'AppraisalController@delEarning');
    Route::post('/createapprasialpage/expenses/delexpense', 'AppraisalController@delExpense');
    Route::post('/createapprasialpage/earnings/delrelayincome', 'AppraisalController@delRelayIncome');
    Route::post('/createapprasialpage/expenses/delloans', 'AppraisalController@delLoans');

// earnings
    Route::post('/createapprasialpage/expenses/addearning', 'BorrowerEarningsController@addEarning');
    Route::get('/createapprasialpage/expenses/getearning', 'BorrowerEarningsController@getEarning');

// relationship incomes
    Route::post('/addmainincome', 'BorrowerEarningsController@addRelationshipIncome');
    Route::get('/getmainincome', 'BorrowerEarningsController@getRelationshipIncome');

// other loans
    Route::post('/appraisalloans/addloan', 'BorrowerOtherLoansController@addLoan');
    Route::get('/appraisalloans/getloan', 'BorrowerOtherLoansController@getLoan');

// ingredients
    Route::post('/addingredient', 'AppraisalIngredientsController@addIngredient');
    Route::get('/getings', 'AppraisalIngredientsController@getIngs');
    Route::get('/getingprice', 'AppraisalIngredientsController@getIngsPrice');

// products
    Route::get('/appraisalproducts', 'AppraisalExpensesProductsController@index');
    Route::post('/addexpenseproduct', 'AppraisalExpensesProductsController@store');

Route::get('/appraisalall', 'AppraisalController@all');


//------------------Approving Loans-------------------

    Route::resource('approving', 'ApprovingController');
    Route::get('/approving/test/{id}', 'ApprovingController@test');
    Route::get('approving/{id}', 'ApprovingController@show');
    Route::get('/bseclector', 'ApprovingController@seclectorB');
    Route::get('/cseclector', 'ApprovingController@seclectorC');
    Route::get('/gseclector', 'ApprovingController@seclectorG');
    Route::post('approving/store/{id}', 'ApprovingController@store');

    Route::get('/createapprasialpage/products', 'AppraisalController@getUnitPrice');
    Route::get('/createapprasialpage/expenses', 'AppraisalController@getExpenses');
    Route::post('/createapprasialpage/expenses/addexpense/', 'AppraisalController@addExpense');
    Route::get('/createapprasialpage/expenses/getexpense', 'AppraisalController@getExpense');

    Route::resource('addexpense', 'ExpensesController');
    Route::resource('otherincomes', 'OtherIncomeController');

    Route::resource('appraisal', 'AppraisalController');
    Route::resource('appraisalearning', 'addAppraisalEarningProductController');

//-------------------printing----------------------------------------
    Route::get('/cheque', 'PrintController@cheque');
    Route::get('/promissory/export/{id}', 'PrintController@exportPromissory');
    Route::get('/agreement/export/{id}', 'PrintController@exportAgreement');

    Route::get('/voucher/export/{voucher_id}', 'PrintController@exportVoucher');
    Route::get('/disbursement/{branchName}/{centerName}', 'PrintController@exportDisbursementCenter');
    Route::get('/disbursement-group/export/{id}', 'PrintController@exportDisbursementGroup');
    Route::get('/guarantor-bond/export/{id}', 'PrintController@exportGuarantorBond');
    Route::get('/repayments/{branchName}/{centerName}', 'PrintController@exportRepayments');
    Route::get('/print-receipt', function () {
        return view('Receipt.receipt');
    });

//------------------------------------witness---------------------

    Route::resource('witness', 'Witness\WitnessController');
    Route::post('/addwitnessbtn', 'Witness\WitnessController@addWitness');

//------------------------------guarantor------------>

    Route::resource('guarantor', 'Guarantor\GuarantorController');

    Route::resource('approved', 'ApprovedController');

    Route::get('/approved/issue/{id}', 'ApprovedController@issue');
    Route::post('/approved/pprCharg/{id}', 'ApprovedController@pprCharg');
    Route::get('/approved/pprChrgView/{id}', 'ApprovedController@pprChrgView');

//------------------------------staff---------------->
    Route::resource('staff', 'StaffController');
    Route::get('/my_profile', 'StaffController@my_profile');
    Route::resource('change_pasword', 'ChangeStaffPasswordController');
// });

//--------------------------Issue Loan----------------------------
    Route::resource('issued', 'IssueLoanContrapprovedoller');

resources/views/admin/centerWiseDue.blade.php
@extends('layouts.master')
@section('content')


{{--//--------------------------------------------------------------------------------------------------------}}

<div class="">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-12 borrower_id">
                    <div class="pull-left">
                        <h2>Due Report</h2>
                    </div>

                </div>

            </div>
        </div>
        <table class="table table-bordered col-12" id="loan_table">

            @isset($mon)
            @foreach ($mon as $item)
            <tr>
                <td>{{ $item->center }}</td>
                <td><?php echo number_format( $item->sum  , 2 , '.' , ',' ) ?></td>
            </tr>
            @endforeach
            @endisset
        </table>
    </div>
</div>
<div class="">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-12 borrower_id">
                    <div class="pull-left">
                        <h2>Collection Report</h2>
                    </div>

                </div>

            </div>
        </div>
        <table class="table table-bordered col-12" id="loan_table">

            @isset($collection)
            @foreach ($collection as $item)
            <tr>
                <td>{{ $item->center }}</td>
                <td><?php echo number_format( $item->collection  , 2 , '.' , ',' ) ?></td>
            </tr>
            @endforeach
            @endisset
        </table>
    </div>
</div>

@endsection

resources/views/admin/change_passwoed.blade.php
@extends('layouts.master')

@section('title')

    Canty International
@endsection

@section('content')
<div class="animated fadeIn">
    <div class="card">
        <div class="card-body">

            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h4>Change Your Current Password</h4>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="/home"> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="card">
        <div class="card-header">
            <strong>Confirm </strong> and Reset
        </div>
        <div class="card-body card-block">
            @if(session()->has('message'))
                <div class="alert alert-success">
                {{ session()->get('message') }}
                </div>
            @endif
            <form action="{{ route('change_pasword.store') }}" method="POST"" method="post" class="">
                @csrf
                <div class="form-group">
                   <input type="password" id="old_p" name="old_p" placeholder="Enter Current Password.." class="form-control">
                    {{-- <span class="help-block">
                        Please enter your current password</span> --}}
                </div>
                <div class="form-group">
                    <input type="password" id="password" name="password" placeholder="Enter New Password.." class="form-control">
                    {{-- <span class="help-block">Please enter your new password</span> --}}
                </div>
                <div class="form-group">

                    <input type="password" id="password_c" name="password_c" placeholder="Confirm New Password.." class="form-control">
                    {{-- <span class="help-block">Confirm your new password</span> --}}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>

                </div>
            </form>
        </div>

    </div>
</div>

@endsection

resources/views/admin/charts.blade.php
@extends('layouts.master')

@section('title')

    Charts | CRM
@endsection
@section('content')
<div class="card  col-6">
    <div class="card-body ">
        <div class="stat-widget-one col-12">
            <canvas id="bar-chart" width="800" height="450"></canvas>
        </div>
        </div>
</div>
<div class="card  col-6">
    <div class="card-body ">
        <div class="stat-widget-one col-12">
            <canvas id="line-chart" width="800" height="450"></canvas>
        </div>
        </div>
</div>
<div class="card  col-6">
    <div class="card-body ">
        <div class="stat-widget-one col-12">
            <canvas id="line-chart2" width="800" height="450"></canvas>
        </div>
        </div>
</div>
<div class="card  col-6">
    <div class="card-body ">
        <div class="stat-widget-one col-12">
            <canvas id="bar-chart-grouped" width="800" height="450"></canvas>
        </div>
        </div>
</div>
<div class="card  col-6">
    <div class="card-body ">
        <div class="stat-widget-one col-12">
            <canvas id="bar-chart2" width="800" height="450"></canvas>
    </div>
    </div>
</div>
<div class="card  col-6">
    <div class="card-body ">
        <div class="stat-widget-one col-12">
        <canvas id="mixed-chart" width="800" height="450"></canvas>
         </div>
    </div>
</div>






                @endsection

@section('scripts')
<script type="text/javascript">
        var ldata = @json($Users);
        var ctdata = @json($Cols);
        var edata = @json($Exps);
        var cloans = @json($Cloans);
        var colCap = @json($ColCap);
        var colInt = @json(($ColInt));
        var colAdv = @json(($ColAdv));
        var arrTot = @json(($ArrTot));
        var arrCap = @json(($ArrCap));
        var arrInt = @json(($ArrInt));


    $(function () {

            new Chart(document.getElementById("bar-chart"), {

    type: 'bar',
    data: {
      labels: ["10000", "15000", "20000", "25000"],
      datasets: [
        {
          label: "Ammount",
          backgroundColor: ["#a7e81b", "#e8711b","#15ce9c","#15a1ce","#c45850"],
          data: ldata
        }
      ]
    },
    options: {
      legend: { display: false },
      title: {
        display: true,
        text: 'Loans Amount By Each Category'
      }
    }
});
// ---
new Chart(document.getElementById("line-chart"), {
  type: 'line',
  data: {
    labels: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
    datasets: [{
        data: cloans,
        label: "Lons ",
        borderColor: "#3e95cd",
        fill: false
      },
    ]
  },
  options: {
    title: {
      display: true,
      text: 'Loans Count By Per Month'
    }
  }
});
// ----
new Chart(document.getElementById("line-chart2"), {
  type: 'line',
  data: {
    labels: [0,"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
    datasets: [{
        data: colInt,
        label: "Interest",
        borderColor: "#3e95cd",
        fill: false
      }, {
        data: colCap,
        label: "Capital",
        borderColor: "#8e5ea2",
        fill: false
      }, {
        data: ctdata,
        label: "Total",
        borderColor: "#3cba9f",
        fill: false
      },
       {
        data: colAdv,
        label: "Advanced",
        borderColor: "#e8711b",
        fill: false
      }
    ]
  },
  options: {
    title: {
      display: true,
      text: 'Collections(per month)'
    }
  }
});

new Chart(document.getElementById("bar-chart-grouped"), {
    type: 'bar',
    data: {
      labels: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
      datasets: [
        {
          label: "Interest",
          backgroundColor: "#3e95cd",
          data: arrInt
        }, {
          label: "Capital",
          backgroundColor: "#8e5ea2",
          data: arrCap
        },{
          label: "Total",
          backgroundColor: "#3cba9f",
          data: arrTot
        }
      ]
    },
    options: {
      title: {
        display: true,
        text: 'Arrears (per month)'
      }
    }
});

new Chart(document.getElementById("bar-chart2"), {
    type: 'bar',
    data: {
      labels: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
      datasets: [
        {
          label: "Expence",
          backgroundColor: "#3cba9f",
          data: edata
        }
      ]
    },
    options: {
      legend: { display: false },
      title: {
        display: true,
        text: 'Expences (per month)'
      }
    }
});

new Chart(document.getElementById("mixed-chart"), {
    type: 'bar',
    data: {
      labels: [0,"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
      datasets: [{
          label: "Income",
          type: "line",
          borderColor: "#8e5ea2",
          data: [408,547,675,734],
          fill: false
        },  {
          label: "Income",
          type: "bar",
          backgroundColor: "rgba(0,0,0,0.2)",
          data: [408,547,675,734],
        },
      ]
    },
    options: {
      title: {
        display: true,
        text: 'Other Incomes'
      },
      legend: { display: false }
    }
});







    })
</script>

@endsection

resources/views/admin/my_profile.blade.php
@extends('layouts.master')

@section('title')

    Canty International
@endsection

@section('content')

<div class="mx-auto">
    <div class="card animated fadeIn">
        <div class="card-header">
            <strong class="card-title mb-3">Profile Card</strong>
        </div>
        <div class="card-body">
            <div class="mx-auto d-block">
                <img class="rounded-circle mx-auto d-block" src="images/admin.jpg" alt="Card image cap">
                <h5 class="text-sm-center mt-2 mb-1">{{$staff_member->name}}</h5>
                <div class="location text-sm-center"><i class="fa fa-user"></i> {{$staff_member->designation}}</div>
                <div class="location text-sm-center"><i class="fa fa-tag"></i> {{$staff_member->nic}}</div>
                <div class="location text-sm-center"><i class="fa fa-flag"></i> {{$staff_member->center}}</div>
                <div class="location text-sm-center"><i class="fa fa-mobile"></i> {{$staff_member->mobile}}</div>
                <div class="location text-sm-center"><i class="fa fa-email"></i> {{$staff_member->mail}}</div>
                <div class="location text-sm-center"><i class="fa fa-map-marker"></i> {{$staff_member->address}}</div>
            </div>
            <hr>
            <div class="card-text text-sm-center">
                <a href="#"><i class="fa fa-facebook pr-1"></i></a>
                <a href="#"><i class="fa fa-twitter pr-1"></i></a>
                <a href="#"><i class="fa fa-linkedin pr-1"></i></a>
                <a href="#"><i class="fa fa-pinterest pr-1"></i></a>
            </div>
        </div>
    </div>
</div>

@endsection