routes/web.php
<?php

// use Symfony\Component\Routing\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout', function () {
    // return abort(404);
    return redirect('/');
});

Route::group(['middleware' => ['auth']], function () {

// Route::get('/location', 'FirebaseController@index');
    // Route::get('/location', function(){
    //     return view ('Location.location');
    // });

// -------------------------------------------------------------- location
    Route::get('/agentforappraisal/{id}/{lat}/{lng}', 'AppraisalController@agentAppraisal');

    Route::get('/execTestRoute', function () {
        return view('execTestRoute');
    })->middleware('executive');

////////////////////////////  add user  /////////////////////////////////////////
    // Route::get('/account/adduser', 'AccountController@addUser')->middleware('admin');
    Route::resource('/account', 'AccountController');

// Route::group(['middleware' => ['auth', 'admin', 'executive']], function () {
    // Route::get('/home', function () {
    //     // return view('admin.dashboard');
    // });
    Route::get('/home', 'HomeController@index');
    Route::get('/home/chrtNreport', 'HomeController@chrtNreport');

//------------------Branch Routs-----------------------

    Route::resource('branch', 'Branch\BranchController');
// Route::get('/showBranch','Branch\BranchController@index');
    //  Route::get('/addbranch','Branch\BranchController@create');
    // Route::get('/storebranch','Branch\BranchController@store');

//------------------Center Routs-----------------------

    Route::resource('center', 'Center\CenterController');
    Route::get('centeri', 'Center\CenterController@index');
    Route::resource('centerleader', 'Center\CenterLeadersController');
    Route::get('/center/edit/{id}', 'Center\CenterLeadersController@edit');
    Route::get('/center/update/{id}', 'Center\CenterLeadersController@update');

//------------------Category Routs---------------------

    Route::resource('category', "CategoryController");
// Route::resource('loan', 'LoanController');

//------------------Routes borrower-------------------

    Route::resource('borrower', 'BorrowerController');
    Route::get('/addborrower', 'BorrowerController@create');
    Route::get('/borrowers', 'BorrowerController@all');
    Route::get('/getcentername', 'BorrowerController@getCenterName');
    Route::get('/getrightcenters', 'BorrowerController@getRightCenters');
    Route::get('/getborrowerscount', 'BorrowerController@getBorrowersCount');
    Route::get('/getborrowerscountofgroup', 'BorrowerController@getborrowerscountofgroup');
    Route::post('/addborrowerajax', 'BorrowerController@addBorrowerAjax');
    Route::get('/borrower/show/{id}', 'BorrowerController@show');
    Route::get('/borrower/edit/{id}', 'BorrowerController@edit');
    Route::get('/addborrower/deleteborrower/{branch}/{center}/{group}', 'BorrowerController@addBorrowerDeleteBorrower');
    Route::post('/addborrower/deleteborrower/{id}', 'BorrowerController@deleteBorrowerChangeVisibility');

    Route::post('/getnic', 'BorrowerController@getNIC');
    Route::post('/checkguardiannic', 'BorrowerController@checkGuardianNIC');

//------------------Loans----------------------------

    Route::resource('loan', 'Loans\LoanController');
    Route::get('/loan/create/rate', 'Loans\LoanController@rate');

    Route::post('/loan/create/addwitness', 'Loans\LoanController@addWitness');
    Route::get('/loan/create/getwitness', 'Loans\LoanController@getWitness');

    Route::get('/loan/create/addbcg', 'Loans\LoanController@addBCG');
    Route::get('/loan/create/witness', 'Loans\LoanController@witness');
    Route::get('/loan/create/take', 'Loans\LoanController@take');

    Route::get('/addloan/getcenters', 'Loans\LoanController@getCenters');
    Route::get('/addloan/getborrowers', 'Loans\LoanController@getBorrowers');
    Route::get('/addloan/getborrowersforrep', 'Loans\LoanController@getBorrowersForRep');
    Route::get('/addloan/getborrowersbynic', 'Loans\LoanController@getBorrowersbynic');
    Route::get('/addloan/getwitnessc', 'Loans\LoanController@getWitnessC');
    Route::get('/addloan/getwitnessa', 'Loans\LoanController@getWitnessA');
    Route::get('/addloan/getloanstage', 'Loans\LoanController@getLoanStage');
    Route::post('/addloanajax', 'Loans\LoanController@store');
    Route::get('/checkcenterleader', 'Loans\LoanController@checkCenterLeader');

//------------------Appraisal-------------------------

    Route::resource('appraisal', 'AppraisalController');
    Route::resource('appraisalearning', 'addAppraisalEarningProductController');
    Route::resource('appraisalcategory', 'addAppraisalProductCategoryController');
    Route::resource('appraisalingredients', 'addAppraisalExpensesProductController');
    Route::post('addAppraisalExpensesProduct', 'addAppraisalExpensesProductController@addAppraisalExpensesProduct');
    Route::get('/createapprasialpage', 'AppraisalController@createAppraisalPage');
    Route::get('/createapprasialpage/products', 'AppraisalController@getUnitPrice');
    Route::get('/createapprasialpage/products', 'AppraisalController@getUnitPrice');
    Route::get('/createapprasialpage/expenses', 'AppraisalController@getExpenses');
    Route::post('/getnicappraisals', 'AppraisalController@getNicAppraisals');
    Route::get('/delprevapp', 'AppraisalController@delPrevApp');
    Route::post('/createapprasialpage/earnings/delearning', 'AppraisalController@delEarning');
    Route::post('/createapprasialpage/expenses/delexpense', 'AppraisalController@delExpense');
    Route::post('/createapprasialpage/earnings/delrelayincome', 'AppraisalController@delRelayIncome');
    Route::post('/createapprasialpage/expenses/delloans', 'AppraisalController@delLoans');

// earnings
    Route::post('/createapprasialpage/expenses/addearning', 'BorrowerEarningsController@addEarning');
    Route::get('/createapprasialpage/expenses/getearning', 'BorrowerEarningsController@getEarning');

// relationship incomes
    Route::post('/addmainincome', 'BorrowerEarningsController@addRelationshipIncome');
    Route::get('/getmainincome', 'BorrowerEarningsController@getRelationshipIncome');

// other loans
    Route::post('/appraisalloans/addloan', 'BorrowerOtherLoansController@addLoan');
    Route::get('/appraisalloans/getloan', 'BorrowerOtherLoansController@getLoan');

// ingredients
    Route::post('/addingredient', 'AppraisalIngredientsController@addIngredient');
    Route::get('/getings', 'AppraisalIngredientsController@getIngs');
    Route::get('/getingprice', 'AppraisalIngredientsController@getIngsPrice');

// products
    Route::get('/appraisalproducts', 'AppraisalExpensesProductsController@index');
    Route::post('/addexpenseproduct', 'AppraisalExpensesProductsController@store');

Route::get('/appraisalall', 'AppraisalController@all');


//------------------Approving Loans-------------------

    Route::resource('approving', 'ApprovingController');
    Route::get('/approving/test/{id}', 'ApprovingController@test');
    Route::get('approving/{id}', 'ApprovingController@show');
    Route::get('/bseclector', 'ApprovingController@seclectorB');
    Route::get('/cseclector', 'ApprovingController@seclectorC');
    Route::get('/gseclector', 'ApprovingController@seclectorG');
    Route::post('approving/store/{id}', 'ApprovingController@store');

    Route::get('/createapprasialpage/products', 'AppraisalController@getUnitPrice');
    Route::get('/createapprasialpage/expenses', 'AppraisalController@getExpenses');
    Route::post('/createapprasialpage/expenses/addexpense/', 'AppraisalController@addExpense');
    Route::get('/createapprasialpage/expenses/getexpense', 'AppraisalController@getExpense');

    Route::resource('addexpense', 'ExpensesController');
    Route::resource('otherincomes', 'OtherIncomeController');

    Route::resource('appraisal', 'AppraisalController');
    Route::resource('appraisalearning', 'addAppraisalEarningProductController');

//-------------------printing----------------------------------------
    Route::get('/cheque', 'PrintController@cheque');
    Route::get('/promissory/export/{id}', 'PrintController@exportPromissory');
    Route::get('/agreement/export/{id}', 'PrintController@exportAgreement');

    Route::get('/voucher/export/{voucher_id}', 'PrintController@exportVoucher');
    Route::get('/disbursement/{branchName}/{centerName}', 'PrintController@exportDisbursementCenter');
    Route::get('/disbursement-group/export/{id}', 'PrintController@exportDisbursementGroup');
    Route::get('/guarantor-bond/export/{id}', 'PrintController@exportGuarantorBond');
    Route::get('/repayments/{branchName}/{centerName}', 'PrintController@exportRepayments');
    Route::get('/print-receipt', function () {
        return view('Receipt.receipt');
    });

//------------------------------------witness---------------------

    Route::resource('witness', 'Witness\WitnessController');
    Route::post('/addwitnessbtn', 'Witness\WitnessController@addWitness');

//------------------------------guarantor------------>

    Route::resource('guarantor', 'Guarantor\GuarantorController');

    Route::resource('approved', 'ApprovedController');

    Route::get('/approved/issue/{id}', 'ApprovedController@issue');
    Route::post('/approved/pprCharg/{id}', 'ApprovedController@pprCharg');
    Route::get('/approved/pprChrgView/{id}', 'ApprovedController@pprChrgView');

//------------------------------staff---------------->
    Route::resource('staff', 'StaffController');
    Route::get('/my_profile', 'StaffController@my_profile');
    Route::resource('change_pasword', 'ChangeStaffPasswordController');
// });

//--------------------------Issue Loan----------------------------
    Route::resource('issued', 'IssueLoanContrapprovedoller');

resources/views/layouts/sidebars/accountant.blade.php
<li class="{{''== request()->path() ?'active':''}}">
    <a href="/loan">View All Loans</a>
</li>
<li class="{{''== request()->path() ?'active':''}}">
    <a href="/loan/create">Add Loan</a>
</li>
<li class="{{''== request()->path() ?'active':''}}">
    <a href="/category/create">Add Loan Category</a>
</li>
<li class="{{''== request()->path() ?'active':''}}">
    <a href="/approved">Approved Loans</a>
</li>

resources/views/layouts/sidebars/agent.blade.php
<li class="{{''== request()->path() ?'active':''}}">
    <a href="/agentsummery" >Today Summery </a>
</li>

<li class="{{''== request()->path() ?'active':''}}">
    <a href="/createapprasialpage" target="_blank">Add Appraisal </a>
</li>
<li>
    <a href="/newrepayments">Collect from Center</a>
</li>
<li>
    <a href="/newnotpaids">Not Paid Collection</a>
</li>
<li class="{{''== request()->path() ?'active':''}}">
    <a href="https://cantylivelocations.firebaseapp.com/upload" target="_blank">
    Location
    </a>
</li>

resources/views/layouts/sidebars/aluthgama_officer.blade.php
<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>CENTER</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        {{-- <li>
            <a href="/center/create">ADD center</a>
        </li> --}}
        <li>
            <a href="/centeri">Add center</a>
        </li>
        <li>
            <a href="/centerleader">Center Leaders</a>
        </li>
    </ul>

</li>
<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>BORROWER</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        {{-- <li>
            <a href="/borrower">ADD borrower</a>
        </li> --}}
        <li>
            <a href="/borrower">Add borrower</a>
        </li>
        <li>
            <a href="/borrowers">View Borrowers</a>
        </li>
        <li>
            <a href="{{ route('groupchange.index') }}">Group Change</a>
        </li>

    </ul>
</li>
<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>APPRAISAL</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        <li>
            <a href="/appraisal">Appraisal</a>
        </li>
        <li>
            <a href="/appraisalall">All</a>
        </li>
        <li class="{{''== request()->path() ?'active':''}}">
            <a href="https://cantylivelocations.firebaseapp.com/upload" target="_blank">
            Location
            </a>
        </li>

    </ul>
</li>
<li class="menu-item-has-children dropdown ">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>LOAN</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        <li>
            <a href="/loan">View All Loans</a>
        </li>
        <li>
            <a href="/loan/create">Add Loan</a>
        </li>
        <li>
            <a href="/verify">Loan Verification</a>
        </li>
        <li>
            <a href="/approved">Approved Loans</a>
        </li>
        <li>
            <a href="/issued">Issued Loans</a>
        </li>
        <li>
            <a href="/issuedcenter">Issued Loans | Center</a>
        </li>
    </ul>
</li>

<li class="menu-item-has-children dropdown animated fadeIn">
    <a href="/postalcode/create">
        Add Postal Code
    </a>
</li>
<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>STAFF</a>
    <ul class="sub-menu children dropdown-menu" id="x">
        <li>
            <a href="{{ route('staff.index') }}"> Staff</a>
        </li>
        <li>
            <a href="{{ route('staff.create') }}">Add Staff</a>
        </li>

    </ul>
</li>

<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>EXPENXES</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        <li>
            <a href="{{ route('company_ex.index')}}">Add Expence</a>
        </li>
        <li>
            <a href="{{ route('ongoing_check.index')}}">Change Ongoing Check</a>
        </li>
        <li>
            <a href="{{ route('compant_ex_cat.index')}}">Add Expences Category</a>
        </li>
        <li>
            <a href="{{ route('approvedex.index')}}">Approved Ex</a>
        </li>
    </ul>
</li>


<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>Repayments</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        <li>
            <a href="/temp/issueIndex"> Issue</a>
        </li>
        <li>
            <a href="/temp/repaymentIndex"> Repayment </a>
        </li>
        <li>
            <a href="/temp/repaymentView"> View </a>
        </li>

    </ul>
</li>

resources/views/layouts/sidebars/branch_acces.blade.php
<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>BRANCH</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        {{-- <li>
            <a href="/branch/create">ADD branch</a>
        </li> --}}
        <li>
            <a href="/branch">Add Branch</a>
        </li>
        <li>
            <a href="#">EDIT Branch</a>
        </li>
    </ul>
</li>

<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>CENTER</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        {{-- <li>
            <a href="/center/create">ADD center</a>
        </li> --}}
        <li>
            <a href="/centeri">Add center</a>
        </li>
        <li>
            <a href="/centerleader">Center Leaders</a>
        </li>
    </ul>

</li>
<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>BORROWER</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        {{-- <li>
            <a href="/borrower">ADD borrower</a>
        </li> --}}
        <li>
            <a href="/borrower">Add borrower</a>
        </li>
        <li>
            <a href="/borrowers">View Borrowers</a>
        </li>

    </ul>
</li>
<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>APPRAISAL</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        <li>
            <a href="/appraisal">Appraisal</a>
        </li>
        <li>
            <a href="/appraisalall">All</a>
        </li>
        <li>
            <a href="/appraisalearning">Appraisal Earings</a>
        </li>
        <li>
        <li>
            <a href="/appraisalproducts">Appraisal Expenses Products</a>
        </li>
        <li>
            <a href="/appraisalingredients">Add Expenses Ingredients</a>
        </li>
        <li class="{{''== request()->path() ?'active':''}}">
            <a href="https://cantylivelocations.firebaseapp.com/upload" target="_blank">
            Location
            </a>
        </li>

    </ul>
</li>
<li class="menu-item-has-children dropdown ">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>LOAN</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        <li>
            <a href="/loan">View All Loans</a>
        </li>
        <li>
            <a href="/loan/create">Add Loan</a>
        </li>
        <li>
            <a href="/verify">Loan Verification</a>
        </li>
        {{-- <li> --}}
            {{-- <a href="/approving">Pending Loans</a> --}}
        {{-- </li> --}}
        <li>
            <a href="/approved">Approved Loans</a>
        </li>
        <li>
            <a href="/issued">Issued Loans</a>
        </li>
        <li>
            <a href="/issuedcenter">Issued Loans | Center</a>
        </li>
        <li>
            <a href="/category">Loan Categories</a>
        </li>

    </ul>
</li>
<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>PAYMENT</a>
    <ul class="sub-menu children dropdown-menu">


        <li>
            <a href="{{ route('guarantor.index') }}">Guarantors</a>
        </li>

        <li>
            <a href="{{ route('witness.index') }}">Witnesses</a>
        </li>

     </ul>
</li>
<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>REPAYMENTS</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        <li>
            <a href="{{route('repayment.index')}}">Center Collection</a>
        </li>
        <li>
            <a href="/repayments/officecollection">Office Collection</a>
        </li>
        <li>
            <a href="/repayments/bulkcollection">Bulk Collection</a>
        </li>
        <li>
            <a href="{{route('repayment_date.index')}}">Repayments For Selected</a>
        </li>
        <li>
            <a href="{{route('repayment_any.index')}}">Old Repayments</a>
        </li>
        <li>
            <a href="#">Upload Repayments - CSV </a>
        </li>
        <li>
            <a href="/repaymentdoc">Repayments Doc</a>
        </li>
        <li>
            <a href="#">Approve Repayments</a>
        </li>
        <li>
            <a href="/repayments/edit">Edit Repayments</a>
        </li>
    </ul>
</li>
{{-- <li class="{{''== request()->path() ?'active':''}}">

<a href="">
    Collateral Register
</a>
</li> --}}
    <li class="menu-item-has-children dropdown">
    <a href="https://cantylivelocations.firebaseapp.com/upload" target="_blank">
        Location
    </a>
</li>
<li class="menu-item-has-children dropdown animated fadeIn">
    <a href="">
        Calendar
    </a>
</li>
<li class="menu-item-has-children dropdown animated fadeIn">
    <a href="/postalcode/create">
        Add Postal Code
    </a>
</li>
<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>STAFF</a>
    <ul class="sub-menu children dropdown-menu" id="x">
        <li>
            <a href="{{ route('staff.index') }}"> Staff</a>
        </li>
        <li>
            <a href="{{ route('staff.create') }}">Add Staff</a>
        </li>

    </ul>
</li>




<li class="menu-item-has-children dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>EXPENXES</a>
    <ul class="sub-menu children dropdown-menu animated fadeIn">
        <li>
            <a href="{{ route('company_ex.index')}}">Add Expence</a>
        </li>
        <li>
            <a href="{{ route('ongoing_check.index')}}">Change Ongoing Check</a>
        </li>
        <li>
            <a href="{{ route('compant_ex_cat.index')}}">Add Expences Category</a>
        </li>
    </ul>
</li>

resources/views/layouts/sidebars/branch_manager.blade.php
<li class="menu-item-has-children dropdown animated fadeIn">
    <a href="/branches/change">
        Change Branch
    </a>
</li>
<li class="{{''== request()->path() ?'active':''}}">
    <a href="/approving">Pending Loans</a>
</li>