routes/web.php
<?php

// use Symfony\Component\Routing\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout', function () {
    // return abort(404);
    return redirect('/');
});

Route::group(['middleware' => ['auth']], function () {

// Route::get('/location', 'FirebaseController@index');
    // Route::get('/location', function(){
    //     return view ('Location.location');
    // });

// -------------------------------------------------------------- location
    Route::get('/agentforappraisal/{id}/{lat}/{lng}', 'AppraisalController@agentAppraisal');

    Route::get('/execTestRoute', function () {
        return view('execTestRoute');
    })->middleware('executive');

////////////////////////////  add user  /////////////////////////////////////////
    // Route::get('/account/adduser', 'AccountController@addUser')->middleware('admin');
    Route::resource('/account', 'AccountController');

// Route::group(['middleware' => ['auth', 'admin', 'executive']], function () {
    // Route::get('/home', function () {
    //     // return view('admin.dashboard');
    // });
    Route::get('/home', 'HomeController@index');
    Route::get('/home/chrtNreport', 'HomeController@chrtNreport');

//------------------Branch Routs-----------------------

    Route::resource('branch', 'Branch\BranchController');
// Route::get('/showBranch','Branch\BranchController@index');
    //  Route::get('/addbranch','Branch\BranchController@create');
    // Route::get('/storebranch','Branch\BranchController@store');

//------------------Center Routs-----------------------

    Route::resource('center', 'Center\CenterController');
    Route::get('centeri', 'Center\CenterController@index');
    Route::resource('centerleader', 'Center\CenterLeadersController');
    Route::get('/center/edit/{id}', 'Center\CenterLeadersController@edit');
    Route::get('/center/update/{id}', 'Center\CenterLeadersController@update');

//------------------Category Routs---------------------

    Route::resource('category', "CategoryController");
// Route::resource('loan', 'LoanController');

//------------------Routes borrower-------------------

    Route::resource('borrower', 'BorrowerController');
    Route::get('/addborrower', 'BorrowerController@create');
    Route::get('/borrowers', 'BorrowerController@all');
    Route::get('/getcentername', 'BorrowerController@getCenterName');
    Route::get('/getrightcenters', 'BorrowerController@getRightCenters');
    Route::get('/getborrowerscount', 'BorrowerController@getBorrowersCount');
    Route::get('/getborrowerscountofgroup', 'BorrowerController@getborrowerscountofgroup');
    Route::post('/addborrowerajax', 'BorrowerController@addBorrowerAjax');
    Route::get('/borrower/show/{id}', 'BorrowerController@show');
    Route::get('/borrower/edit/{id}', 'BorrowerController@edit');
    Route::get('/addborrower/deleteborrower/{branch}/{center}/{group}', 'BorrowerController@addBorrowerDeleteBorrower');
    Route::post('/addborrower/deleteborrower/{id}', 'BorrowerController@deleteBorrowerChangeVisibility');

    Route::post('/getnic', 'BorrowerController@getNIC');
    Route::post('/checkguardiannic', 'BorrowerController@checkGuardianNIC');

//------------------Loans----------------------------

    Route::resource('loan', 'Loans\LoanController');
    Route::get('/loan/create/rate', 'Loans\LoanController@rate');

    Route::post('/loan/create/addwitness', 'Loans\LoanController@addWitness');
    Route::get('/loan/create/getwitness', 'Loans\LoanController@getWitness');

    Route::get('/loan/create/addbcg', 'Loans\LoanController@addBCG');
    Route::get('/loan/create/witness', 'Loans\LoanController@witness');
    Route::get('/loan/create/take', 'Loans\LoanController@take');

    Route::get('/addloan/getcenters', 'Loans\LoanController@getCenters');
    Route::get('/addloan/getborrowers', 'Loans\LoanController@getBorrowers');
    Route::get('/addloan/getborrowersforrep', 'Loans\LoanController@getBorrowersForRep');
    Route::get('/addloan/getborrowersbynic', 'Loans\LoanController@getBorrowersbynic');
    Route::get('/addloan/getwitnessc', 'Loans\LoanController@getWitnessC');
    Route::get('/addloan/getwitnessa', 'Loans\LoanController@getWitnessA');
    Route::get('/addloan/getloanstage', 'Loans\LoanController@getLoanStage');
    Route::post('/addloanajax', 'Loans\LoanController@store');
    Route::get('/checkcenterleader', 'Loans\LoanController@checkCenterLeader');

//------------------Appraisal-------------------------

    Route::resource('appraisal', 'AppraisalController');
    Route::resource('appraisalearning', 'addAppraisalEarningProductController');
    Route::resource('appraisalcategory', 'addAppraisalProductCategoryController');
    Route::resource('appraisalingredients', 'addAppraisalExpensesProductController');
    Route::post('addAppraisalExpensesProduct', 'addAppraisalExpensesProductController@addAppraisalExpensesProduct');
    Route::get('/createapprasialpage', 'AppraisalController@createAppraisalPage');
    Route::get('/createapprasialpage/products', 'AppraisalController@getUnitPrice');
    Route::get('/createapprasialpage/products', 'AppraisalController@getUnitPrice');
    Route::get('/createapprasialpage/expenses', 'AppraisalController@getExpenses');
    Route::post('/getnicappraisals', 'AppraisalController@getNicAppraisals');
    Route::get('/delprevapp', 'AppraisalController@delPrevApp');
    Route::post('/createapprasialpage/earnings/delearning', 'AppraisalController@delEarning');
    Route::post('/createapprasialpage/expenses/delexpense', 'AppraisalController@delExpense');
    Route::post('/createapprasialpage/earnings/delrelayincome', 'AppraisalController@delRelayIncome');
    Route::post('/createapprasialpage/expenses/delloans', 'AppraisalController@delLoans');

// earnings
    Route::post('/createapprasialpage/expenses/addearning', 'BorrowerEarningsController@addEarning');
    Route::get('/createapprasialpage/expenses/getearning', 'BorrowerEarningsController@getEarning');

// relationship incomes
    Route::post('/addmainincome', 'BorrowerEarningsController@addRelationshipIncome');
    Route::get('/getmainincome', 'BorrowerEarningsController@getRelationshipIncome');

// other loans
    Route::post('/appraisalloans/addloan', 'BorrowerOtherLoansController@addLoan');
    Route::get('/appraisalloans/getloan', 'BorrowerOtherLoansController@getLoan');

// ingredients
    Route::post('/addingredient', 'AppraisalIngredientsController@addIngredient');
    Route::get('/getings', 'AppraisalIngredientsController@getIngs');
    Route::get('/getingprice', 'AppraisalIngredientsController@getIngsPrice');

// products
    Route::get('/appraisalproducts', 'AppraisalExpensesProductsController@index');
    Route::post('/addexpenseproduct', 'AppraisalExpensesProductsController@store');

Route::get('/appraisalall', 'AppraisalController@all');


//------------------Approving Loans-------------------

    Route::resource('approving', 'ApprovingController');
    Route::get('/approving/test/{id}', 'ApprovingController@test');
    Route::get('approving/{id}', 'ApprovingController@show');
    Route::get('/bseclector', 'ApprovingController@seclectorB');
    Route::get('/cseclector', 'ApprovingController@seclectorC');
    Route::get('/gseclector', 'ApprovingController@seclectorG');
    Route::post('approving/store/{id}', 'ApprovingController@store');

    Route::get('/createapprasialpage/products', 'AppraisalController@getUnitPrice');
    Route::get('/createapprasialpage/expenses', 'AppraisalController@getExpenses');
    Route::post('/createapprasialpage/expenses/addexpense/', 'AppraisalController@addExpense');
    Route::get('/createapprasialpage/expenses/getexpense', 'AppraisalController@getExpense');

    Route::resource('addexpense', 'ExpensesController');
    Route::resource('otherincomes', 'OtherIncomeController');

    Route::resource('appraisal', 'AppraisalController');
    Route::resource('appraisalearning', 'addAppraisalEarningProductController');

//-------------------printing----------------------------------------
    Route::get('/cheque', 'PrintController@cheque');
    Route::get('/promissory/export/{id}', 'PrintController@exportPromissory');
    Route::get('/agreement/export/{id}', 'PrintController@exportAgreement');

    Route::get('/voucher/export/{voucher_id}', 'PrintController@exportVoucher');
    Route::get('/disbursement/{branchName}/{centerName}', 'PrintController@exportDisbursementCenter');
    Route::get('/disbursement-group/export/{id}', 'PrintController@exportDisbursementGroup');
    Route::get('/guarantor-bond/export/{id}', 'PrintController@exportGuarantorBond');
    Route::get('/repayments/{branchName}/{centerName}', 'PrintController@exportRepayments');
    Route::get('/print-receipt', function () {
        return view('Receipt.receipt');
    });

//------------------------------------witness---------------------

    Route::resource('witness', 'Witness\WitnessController');
    Route::post('/addwitnessbtn', 'Witness\WitnessController@addWitness');

//------------------------------guarantor------------>

    Route::resource('guarantor', 'Guarantor\GuarantorController');

    Route::resource('approved', 'ApprovedController');

    Route::get('/approved/issue/{id}', 'ApprovedController@issue');
    Route::post('/approved/pprCharg/{id}', 'ApprovedController@pprCharg');
    Route::get('/approved/pprChrgView/{id}', 'ApprovedController@pprChrgView');

//------------------------------staff---------------->
    Route::resource('staff', 'StaffController');
    Route::get('/my_profile', 'StaffController@my_profile');
    Route::resource('change_pasword', 'ChangeStaffPasswordController');
// });

//--------------------------Issue Loan----------------------------
    Route::resource('issued', 'IssueLoanContrapprovedoller');

app/Borrower.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Borrower extends Model
{
    protected $table = 'borrowers';
    protected $fillable = [
        // 'application_no',
        'branch',
        'branch_no',
        'center',
        'group_no',
        'borrower_no',
        'full_name',
        'nic',
        'birthday',
        'address',
        'gender',
        'civil_status',
        'related_civil_status',
        'h_g_name',
        'h_g_number',
        'h_g_sallery',
        'lp_no',
        'mobile_no',
        'email',
        'occupation',
        'remarks',
        'status',
        'n_of_loans'
    ];
    protected $primaryKey = 'borrower_no';
    public $incrementing = false;
    protected $keyType = 'string';
}

app/Http/Controllers/BorrowerController.php
<?php

namespace App\Http\Controllers;

use App\Borrower;
use App\Branch;
use App\Center;
use App\CenterLeader;
use App\Loan;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB as FacadesDB;

class BorrowerController extends Controller
{

    public function index()
    {

        // borrowers count
        $borrowersCount = count(Borrower::all());
        $borrowersCount++;

        // get branches
        $branches = Branch::where('branch_name',Auth::user()->branch)->get();
        // get centers
        $centers = Center::all();

        //       return view('Borrower.borrowerindex');
        $borrowers = Borrower::latest()->paginate(1000);
        return view('Borrower.borrowerindex', compact('borrowers', 'borrowersCount', 'branches', 'centers'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
    }

    public function all()
    {
        $borrowers = Borrower::where('visibility',1)->get();
        return view('Borrower.borrowersindex', compact('borrowers'));
    }

    public function store(Request $request)
    {

        $request->validate([

            // 'application_no'  => 'required | numeric',
            'branch' => 'required',
            // 'branch_no' => 'required',
            'center' => 'required',
            'group_no'  => 'required',
            'borrower_no'  => 'required',
            'full_name' => 'required ',
            'nic' => 'required',
            'birthday' => 'required',
            'gender' => 'required',
            'address' => 'required',
            // 'lp_no' => 'required | numeric',
            'mobile_no' => 'required | numeric',
            // 'email' => 'required ',
            // 'occupation' => 'required',
            // 'requested_amount' => 'required | numeric',
            // 'duration_weeks' => 'required | numeric',
            // 'loan_stage' => 'required'
        ]);

        Borrower::create($request->all());

        if ($request->remarks == 'Center Leader') {
            $leader = new CenterLeader;
            $leader->borrower_id = $request->borrower_no;
            $leader->branch = $request->branch;
            $leader->center = $request->center;
            $leader->save();
        }

        return redirect()->route('borrower.index')
            ->with('success', 'Borrower created successfully.');
    }


    public function show($id)
    {
        $req = $id;
        $borrower = Borrower::where('borrower_no', $req)->first();
        return view('Borrower.viewborrower', compact('borrower'));
    }


    public function edit($id)
    {
        $req = $id;
        $borrower = Borrower::where('borrower_no', $req)->first();
        return view('Borrower.editborrower', compact('borrower'));
    }


    public function update(Request $request, Borrower $borrower)
    {

        $borrower->update($request->all());
        return redirect()->route('borrower.index')
            ->with('success', 'Borrower updated successfully');
    }

    public function destroy(Borrower $borrower)
    {
        $borrower->delete();

        return redirect()->route('borrower.index')
            ->with('success', 'Borrower deleted successfully');
    }

    public function getCenterName(Request $request)
    {
        $center = Center::where('center_name', $request->name)->first();
        $center = $center->center_no;
        return response()->json($center);
    }

    public function getRightCenters(Request $request)
    {
        // $branch = Branch::where('branch_name', $request->branch)->first();
        $centers = Center::where('branch_no', $request->branch)->get();
        return response()->json($centers);
    }

    public function getNIC(request $request)
    {
        $nic = Borrower::where('nic', $request->nic)->where('is_deactivated',0)->first();

        if ($nic) {
            return response()->json('NIC already registered');
        } else {
            return response()->json('NIC available');
        }
    }

    public function getBorrowersCount(Request $request)
    {
        $borrowers = Borrower::where('branch', $request->branch)
            ->where('center', $request->center)
            // ->where('group_no', $request->group)
            ->get();


        return response()->json($borrowers);
    }
    public function getborrowerscountofgroup(Request $request)
    {

        $groupCount = Borrower::where('branch', $request->branch)
            ->where('center', $request->center)
            ->where('group_no', $request->group)
            ->where('visibility',1)
            ->get();

        return response()->json($groupCount);
    }
    public function view($id)
    {
        $loan = Loan::where('id', $id)->first();
        $borrower = Borrower::where('borrower_no', $loan->borrower_no)->first();
        return view('Loans.showLoan', compact('loan', 'borrower'));
    }

    public function addBorrowerAjax(Request $request)
    {

        Borrower::create($request->all());

        if ($request->remarks == 'Center Leader') {
            $leader = new CenterLeader;
            $leader->borrower_id = $request->borrower_no;
            $leader->branch = $request->branch;
            $leader->center = $request->center;
            $leader->save();
        }
        return response()->json('borrower_added');
    }


    public function capital()
    {
        // $borrowers=Borrower::all();
        // foreach($borrowers as $borrowe)
        // Borrower::where('status','active')->update(['full_name'=>ucwords($borrowe->full_name)]);

        $bs = DB::table('borrowers')->get();
        foreach ($bs as $b) {
            $name = $b->address;
            $lc = strtolower($name);
            $uppercased = ucwords($lc);
            // $b->full_name=$uppercased;
            // $b->save();

            Borrower::where('id', $b->id)->update(['address' => $uppercased]);
        }

        return $uppercased;
    }

    public function addBorrowerDeleteBorrower($branch, $center, $group)
    {
        $borrowers = Borrower::where('branch', $branch)
            ->where('center', $center)
            ->where('group_no', $group)
            ->where('visibility', 1)
            ->get();
        return view('Borrower.deleteGroupBorrower', compact('borrowers'));
    }

    public function deleteBorrowerChangeVisibility($id){
        $borrower = Borrower::where('id', $id)->first();

        $status =Loan::where('borrower_no',$borrower->borrower_no)->where('status','!=','SETTLED')->get();
        // return count($status);
        if(count($status) == 0){

            $borrower->visibility = 0;
            $borrower->save();
            return redirect()->back();
        } else{
            return redirect()->back()->with('error', 'Sorry this borrower has incomplete');

        }

    }

    public function checkGuardianNIC(Request $request){
        $nic = Borrower::where('lp_no', $request->nic)->first();

        if ($nic) {
            return response()->json('NIC already registered');
        } else {
            return response()->json('NIC available');
        }
    }
}

resources/views/Borrower/allborrowers.blade.php
@extends('layouts.master')

@section('title')

    Canty International
@endsection

@section('content')

    {{-- <h1>addbranch</h1> --}}

@endsection

@section('scripts')

@endsection

resources/views/Borrower/borrowersindex.blade.php
@extends('layouts.master')
@section('title')


@endsection
@section('content')
<div class="animated fadeIn">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-12 ">
                    <div class="pull-left">
                        <h2>Borrowers All</h2>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="card animated fadeIn" style="width: 100%;">
    <div class="card-body">
        <table class="table table-bordered" id="data_table">
            <thead>
            <tr>
                <th>Center</th>
                <th>Group No</th>
                <th>Name</th>
                <th>NIC No</th>
                <th>Borrower No</th>
                <th>Address</th>
                <th>Mobile</th>
                <th>Relation Mobile</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($borrowers as $borrower)
            <tr>
                <td>{{ $borrower->center}}</td>
                <td>{{ $borrower->group_no}}</td>
                <td>{{ $borrower->full_name}}</td>
                <td>{{ $borrower->nic }}</td>
                <td>{{ $borrower->borrower_no }}</td>
                <td>{{ $borrower->address }}</td>
                <td>{{ $borrower->mobile_no  }}</td>
                <td>{{ $borrower->h_g_number }}</td>

            </tr>
            @endforeach
        </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
         $('#data_table').DataTable();
    } );

</script>

@endsection

resources/views/Borrower/deleteGroupBorrower.blade.php
@extends('layouts.master')

@section('title')

Canty International
@endsection

@section('content')
<div class="card">

    <table class="table">
        <tr>
            <th>Name</th>
            <th>NIC</th>
            <th>Borrower No</th>
            <th></th>
        </tr>

        @foreach($borrowers as $borrower)
        <tr>
            <td>{{$borrower->full_name}}</td>
            <td>{{$borrower->nic}}</td>
            <td>{{$borrower->borrower_no}}</td>
            <td>
                <form action="/addborrower/deleteborrower/{{$borrower->id}}" method="post">
                    @csrf
                    <button type="submit" class="btn btn-danger btn-sm">Remove Borrower</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
</div>
@endsection

@section('scripts')

@endsection

resources/views/Borrower/editborrower.blade.php
@extends('layouts.master')
@section('title')

    Canty International
@endsection
@section('content')
<div class="container">
    <div class="card">
        <div   class="card-body">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Branch</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('borrower.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Warning!</strong> Please check input field code<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

            <form action="{{ route('borrower.update',$borrower->borrower_no) }}" method="POST">
                @csrf
                @method('PUT')

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Branch :</strong>
                            <input type="text" disabled name="branch" value="{{ $borrower->branch }}" class="form-control" placeholder="Branch">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Center:</strong>
                            <input type="text" name="center" disabled value="{{ $borrower->center }}" class="form-control" placeholder="Center">
                        </div>
                    </div>
                  <!-- <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Branch No:</strong>
                            <input type="text" name="branch_no" value="{{ $borrower->branch_no }}" class="form-control" placeholder="Branch No">
                        </div>
                    </div>  -->

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Group No:</strong>
                            <input type="text" name="group_no" disabled value="{{ $borrower->group_no }}" class="form-control" placeholder="Group No">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Unique Id:</strong>
                            <input type="text" name="borrower_no" disabled value="{{ $borrower->borrower_no }}" class="form-control" placeholder="Unique Id">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Full NAme:</strong>
                            <input type="text" name="full_name"  id="full_name" value="{{ $borrower->full_name }}" oninput="toCap(this.value, this.id)" class="form-control" placeholder="Branch Mobile">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Address:</strong>
                            <input type="text" name="address" id="address" value="{{ $borrower->address }}" oninput="toCap(this.value, this.id)" class="form-control" placeholder="Address">
                        </div>
                    </div>
                    <!-- <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Application No:</strong>
                            <input type="text" name="application_no" value="{{ $borrower->application_no }}" class="form-control" placeholder="Application No">
                        </div>
                    </div> -->


                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>NIC :</strong>
                            <input type="text" name="nic" disabled value="{{ $borrower->nic }}"  class="form-control" placeholder="NIC">
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <strong>Borrower Contact:</strong>
                            <input type="text" name="mobile_no" value="{{ $borrower->mobile_no }}" class="form-control" placeholder="Branch Email">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Birthday:</strong>
                            <input type="text" name="birthday" value="{{ $borrower->birthday }}" class="form-control" placeholder="Birthday">
                        </div>
                    </div>


                    <div class="col-xs-8 col-sm-8 col-md-8">
                        <div class="form-group">
                            <strong>Civil Status:</strong>
                            <input type="text" name="civil_status" value="{{ $borrower->civil_status }}" class="form-control" placeholder="Civil Status">
                        </div>
                    </div>

                    <div class="col-xs-8 col-sm-8 col-md-8">

                        <div class="form-group">
                            <strong>Joint Holder Name:</strong>
                            <input type="text" name="h_g_name" id="h_g_name" value="{{ $borrower->h_g_name }}" oninput="toCap(this.value, this.id)" class="form-control" placeholder="Name">
                        </div>
                     </div> <div class="col-xs-4 col-sm-4 col-md-4">
                        <div class="form-group">
                            <strong>Joint Holder Contact:</strong>
                            <input type="text" name="h_g_number" value="{{ $borrower->h_g_number }}" class="form-control" placeholder="Mobile Number">
                        </div>
                    </div>
                  <div class="col-xs-4 col-sm-4 col-md-4">
                        {{-- <div class="form-group">
                            <strong>Salary:</strong>
                            <input type="text" name="h_g_sallery" value="{{ $borrower->h_g_sallery }}" class="form-control" placeholder="Sallery">
                        </div> --}}
                    {{-- </div> --}}
                    {{-- <div class="col-xs-6 col-sm-6 col-md-6"> --}}
                        <div class="form-group">
                            <strong>Joint Holder NIC:</strong>
                            <input type="text" name="lp_no" value="{{ $borrower->lp_no }}" class="form-control" placeholder="LP Number">
                        </div>
                    </div>

                    <!-- <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>E Mail:</strong>
                            <input type="text" name="email" value="{{ $borrower->email }}" class="form-control" placeholder="E Mail">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Occupation:</strong>
                            <input type="text" name="occupation" value="{{ $borrower->occupation }}" class="form-control" placeholder="Occupation">
                        </div>
                    </div> -->
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            {{-- <strong>Remarks:</strong> --}}
                            <input type="hidden" name="occupation" id="occupation" value="{{ $borrower->remarks }}" oninput="toCap(this.value, this.id)" class="form-control" placeholder="Occupation">
                        </div>
                    </div>
                     <!-- <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Amount:</strong>
                            <input type="text" name="requested_amount" value="{{ $borrower->requested_amount }}" class="form-control" placeholder="Amount">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Duration(weeks):</strong>
                            <input type="text" name="duration_weeks" value="{{ $borrower->duration_weeks }}" class="form-control" placeholder="Duration(weeks)">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Loan Stage:</strong>
                            <input type="text" name="loan_stage" value="{{ $borrower->loan_stage }}" class="form-control" placeholder="Loan Stage">
                        </div>
                    </div>  -->

                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
@endsection
@section('scripts')

@endsection